### ISSUE TITLE
Use POST methods for annotation

### ISSUE THREAD

**Issue by zhx828** [oncokb/oncokb-annotator#62]
Replace current GET method with POST, so we can decrease the workload
https://www.oncokb.org/swagger-ui/index.html

- [x] Understand how function `makeoncokbrequest` and `pulloncokb` works in `AnnotatorCore.py`
- [x] Understand why we want to change GET to POST
- [x] Use `pull_mutation_info` as example where uses `pulloncokb`:  we should call `pull_mutation_info` after reading 50 rows instead of calling it every row.

- [x] Understand how method `processalterationevents` works.
It takes a file and reads the row on line 269.
It processes the row and gathers all necessary information before calling pull_mutation_info

- [x] Change the `pull_mutation_info` arguments to a list of class  which includes hugo, protein_change, consequence, start, end, cancer_type
From last step, you understand how the `processalterationevents` works. Instead of reading one row then call `pull_mutation_info`, we want to read 50 rows and put processed data into a list. Then past the list to `pull_mutation_info`. 

- [x] Process 50 rows in `pulloncokb` and return 50rows response and append the result to the file
- [x] If the api failed, we should try to resend the api again.(Sometimes the system may not be stable for overwhelming requests, but there should always be a service available)
